### ISSUE TITLE
Maquetar página de Simulación de Fase Final

### ISSUE THREAD

**Issue by McJaben** [Grupo-LabProg/simuladorMundial2026#5]
# Página con los brackets y los partidos a simular en la fase final

Habría que agregar una tabla o un cuadro con los **participantes**, con los brackets.
Información que podría incluir:

- "Columna" con el nombre de la etapa (octavos, cuartos, semis, etc.)
- Espacios donde se colocan las selecciones que llegan a esa etapa.
- Espacio para colocar predicción del resultado y/o posibilidad de simularlo, partido por partido.

### Ejemplo de la vista:

![image](https://github.com/user-attachments/assets/ab25b26a-9412-4fc3-987e-d348a0fd0c84)

**Comment by kevinquintero11** [comment]
![782317a324979aa2204427b2b7e48b7c](https://github.com/user-attachments/assets/9e031d0b-4319-439f-9076-b16135baf922)
